// src/constants/vocabularySuggestions.js

export const VOCAB_SUGGESTIONS = {
  // ==========================================
  // FAMILY - Gia đình
  // ==========================================
  FAMILY: {
    A1: [
      { en: "mother", vi: "mẹ" },
      { en: "father", vi: "bố" },
      { en: "sister", vi: "chị/em gái" },
      { en: "brother", vi: "anh/em trai" },
      { en: "baby", vi: "em bé" },
      { en: "home", vi: "nhà" },
      { en: "love", vi: "yêu" },
      { en: "family", vi: "gia đình" },
      { en: "big", vi: "to/lớn" },
      { en: "small", vi: "nhỏ" },
      { en: "son", vi: "con trai" },
      { en: "daughter", vi: "con gái" },
      { en: "parents", vi: "bố mẹ" },
      { en: "grandma", vi: "bà" },
      { en: "grandpa", vi: "ông" },
      { en: "aunt", vi: "cô/dì" },
      { en: "uncle", vi: "chú/bác" },
      { en: "cousin", vi: "anh chị em họ" },
      { en: "wife", vi: "vợ" },
      { en: "husband", vi: "chồng" },
    ],
    A2: [
      { en: "grandmother", vi: "bà" },
      { en: "grandfather", vi: "ông" },
      { en: "relative", vi: "họ hàng" },
      { en: "together", vi: "cùng nhau" },
      { en: "dinner", vi: "bữa tối" },
      { en: "nephew", vi: "cháu trai" },
      { en: "niece", vi: "cháu gái" },
      { en: "twin", vi: "sinh đôi" },
      { en: "married", vi: "đã kết hôn" },
      { en: "single", vi: "độc thân" },
      { en: "divorce", vi: "ly hôn" },
      { en: "wedding", vi: "đám cưới" },
      { en: "birth", vi: "sự sinh" },
      { en: "grow up", vi: "lớn lên" },
      { en: "take care", vi: "chăm sóc" },
      { en: "children", vi: "con cái" },
      { en: "parents", vi: "bố mẹ" },
      { en: "cousin", vi: "anh chị em họ" },
      { en: "uncle", vi: "chú/bác" },
      { en: "aunt", vi: "cô/dì" },
    ],
    B1: [
      { en: "sibling", vi: "anh chị em ruột" },
      { en: "generation", vi: "thế hệ" },
      { en: "relationship", vi: "mối quan hệ" },
      { en: "support", vi: "hỗ trợ" },
      { en: "raise", vi: "nuôi dạy" },
      { en: "responsibility", vi: "trách nhiệm" },
      { en: "household", vi: "hộ gia đình" },
      { en: "bond", vi: "sự gắn kết" },
      { en: "nuclear", vi: "hạt nhân (gia đình)" },
      { en: "extended", vi: "mở rộng" },
      { en: "upbringing", vi: "sự nuôi dạy" },
      { en: "ancestor", vi: "tổ tiên" },
      { en: "heritage", vi: "di sản" },
      { en: "tradition", vi: "truyền thống" },
      { en: "loyalty", vi: "lòng trung thành" },
      { en: "conflict", vi: "xung đột" },
      { en: "harmony", vi: "sự hòa thuận" },
      { en: "nurture", vi: "nuôi dưỡng" },
      { en: "guardian", vi: "người giám hộ" },
      { en: "adopt", vi: "nhận nuôi" },
    ],
    B2: [
      { en: "custody", vi: "quyền giám hộ" },
      { en: "kinship", vi: "quan hệ họ hàng" },
      { en: "domestic", vi: "trong gia đình" },
      { en: "reunion", vi: "cuộc đoàn tụ" },
      { en: "in-laws", vi: "bố mẹ vợ/chồng" },
      { en: "stepfamily", vi: "gia đình ghép" },
      { en: "single-parent", vi: "gia đình đơn thân" },
      { en: "breadwinner", vi: "trụ cột gia đình" },
      { en: "matriarch", vi: "người phụ nữ nắm quyền" },
      { en: "patriarch", vi: "người đàn ông nắm quyền" },
      { en: "lineage", vi: "dòng dõi" },
      { en: "descendant", vi: "hậu duệ" },
      { en: "genealogy", vi: "gia phả" },
      { en: "estrangement", vi: "sự xa cách" },
      { en: "cohesion", vi: "sự gắn kết" },
      { en: "upbringing", vi: "sự nuôi dạy" },
      { en: "heritage", vi: "di sản" },
      { en: "ancestor", vi: "tổ tiên" },
      { en: "nurture", vi: "nuôi dưỡng" },
      { en: "adopt", vi: "nhận nuôi" },
    ],
    C1: [
      { en: "paternal", vi: "thuộc về bố" },
      { en: "maternal", vi: "thuộc về mẹ" },
      { en: "consanguinity", vi: "quan hệ huyết thống" },
      { en: "affinity", vi: "quan hệ thông gia" },
      { en: "progeny", vi: "con cháu" },
      { en: "ancestral", vi: "thuộc tổ tiên" },
      { en: "dissolution", vi: "sự tan rã" },
      { en: "nurturance", vi: "sự nuôi dưỡng" },
      { en: "filiation", vi: "quan hệ cha con" },
      { en: "kindred", vi: "họ hàng" },
      { en: "affinal", vi: "thuộc thông gia" },
      { en: "dynastic", vi: "thuộc triều đại" },
      { en: "obligation", vi: "nghĩa vụ" },
      { en: "genealogy", vi: "gia phả" },
      { en: "lineage", vi: "dòng dõi" },
      { en: "matriarch", vi: "mẫu hệ" },
      { en: "patriarch", vi: "phụ hệ" },
      { en: "estrangement", vi: "sự xa cách" },
      { en: "cohesion", vi: "sự gắn kết" },
      { en: "upbringing", vi: "sự nuôi dạy" },
    ],
    C2: [
      { en: "patrilineal", vi: "theo dòng bố" },
      { en: "matrilineal", vi: "theo dòng mẹ" },
      { en: "endogamy", vi: "hôn nhân nội tộc" },
      { en: "exogamy", vi: "hôn nhân ngoại tộc" },
      { en: "primogeniture", vi: "quyền con trưởng" },
      { en: "avuncular", vi: "như chú bác" },
      { en: "uxorial", vi: "thuộc vợ" },
      { en: "filial", vi: "hiếu thảo" },
      { en: "conjugal", vi: "thuộc vợ chồng" },
      { en: "agnatic", vi: "theo họ nội" },
      { en: "consanguinity", vi: "huyết thống" },
      { en: "affinity", vi: "thông gia" },
      { en: "progeny", vi: "con cháu" },
      { en: "ancestral", vi: "tổ tiên" },
      { en: "dissolution", vi: "tan rã" },
      { en: "nurturance", vi: "nuôi dưỡng" },
      { en: "filiation", vi: "cha con" },
      { en: "kindred", vi: "họ hàng" },
      { en: "affinal", vi: "thông gia" },
      { en: "dynastic", vi: "triều đại" },
    ],
  },

  // ==========================================
  // WORK - Công việc
  // ==========================================
  WORK: {
    A1: [
      { en: "job", vi: "công việc" },
      { en: "work", vi: "làm việc" },
      { en: "office", vi: "văn phòng" },
      { en: "boss", vi: "sếp" },
      { en: "money", vi: "tiền" },
      { en: "start", vi: "bắt đầu" },
      { en: "finish", vi: "kết thúc" },
      { en: "help", vi: "giúp" },
      { en: "team", vi: "đội nhóm" },
      { en: "meeting", vi: "cuộc họp" },
      { en: "desk", vi: "bàn làm việc" },
      { en: "phone", vi: "điện thoại" },
      { en: "email", vi: "thư điện tử" },
      { en: "computer", vi: "máy tính" },
      { en: "paper", vi: "giấy" },
      { en: "pen", vi: "bút" },
      { en: "time", vi: "thời gian" },
      { en: "day", vi: "ngày" },
      { en: "night", vi: "đêm" },
      { en: "busy", vi: "bận rộn" },
    ],
    A2: [
      { en: "career", vi: "sự nghiệp" },
      { en: "colleague", vi: "đồng nghiệp" },
      { en: "manager", vi: "quản lý" },
      { en: "salary", vi: "lương" },
      { en: "hour", vi: "giờ" },
      { en: "project", vi: "dự án" },
      { en: "company", vi: "công ty" },
      { en: "employee", vi: "nhân viên" },
      { en: "schedule", vi: "lịch trình" },
      { en: "task", vi: "nhiệm vụ" },
      { en: "report", vi: "báo cáo" },
      { en: "client", vi: "khách hàng" },
      { en: "customer", vi: "khách hàng" },
      { en: "shift", vi: "ca làm" },
      { en: "break", vi: "giờ nghỉ" },
      { en: "uniform", vi: "đồng phục" },
      { en: "training", vi: "đào tạo" },
      { en: "staff", vi: "nhân viên" },
      { en: "office", vi: "văn phòng" },
      { en: "busy", vi: "bận rộn" },
    ],
    B1: [
      { en: "promotion", vi: "thăng chức" },
      { en: "responsibility", vi: "trách nhiệm" },
      { en: "deadline", vi: "hạn chót" },
      { en: "interview", vi: "phỏng vấn" },
      { en: "contract", vi: "hợp đồng" },
      { en: "overtime", vi: "làm thêm giờ" },
      { en: "workload", vi: "khối lượng công việc" },
      { en: "skill", vi: "kỹ năng" },
      { en: "experience", vi: "kinh nghiệm" },
      { en: "position", vi: "vị trí" },
      { en: "resume", vi: "sơ yếu lý lịch" },
      { en: "application", vi: "đơn xin việc" },
      { en: "benefit", vi: "phúc lợi" },
      { en: "vacation", vi: "kỳ nghỉ" },
      { en: "supervisor", vi: "giám sát viên" },
      { en: "department", vi: "phòng ban" },
      { en: "presentation", vi: "thuyết trình" },
      { en: "teamwork", vi: "làm việc nhóm" },
      { en: "colleague", vi: "đồng nghiệp" },
      { en: "meeting", vi: "cuộc họp" },
    ],
    B2: [
      { en: "negotiate", vi: "đàm phán" },
      { en: "performance", vi: "hiệu suất" },
      { en: "efficiency", vi: "hiệu quả" },
      { en: "productivity", vi: "năng suất" },
      { en: "leadership", vi: "lãnh đạo" },
      { en: "subordinate", vi: "cấp dưới" },
      { en: "delegate", vi: "ủy quyền" },
      { en: "initiative", vi: "sáng kiến" },
      { en: "compensation", vi: "đền bù" },
      { en: "hierarchy", vi: "hệ thống cấp bậc" },
      { en: "appraisal", vi: "đánh giá" },
      { en: "incentive", vi: "khuyến khích" },
      { en: "bonus", vi: "tiền thưởng" },
      { en: "mentor", vi: "người cố vấn" },
      { en: "networking", vi: "kết nối" },
      { en: "freelance", vi: "làm tự do" },
      { en: "remote", vi: "làm từ xa" },
      { en: "collaboration", vi: "hợp tác" },
      { en: "accountability", vi: "trách nhiệm giải trình" },
      { en: "promotion", vi: "thăng chức" },
    ],
    C1: [
      { en: "entrepreneur", vi: "doanh nhân" },
      { en: "remuneration", vi: "thù lao" },
      { en: "redundancy", vi: "sa thải" },
      { en: "outsourcing", vi: "thuê ngoài" },
      { en: "delegation", vi: "ủy quyền" },
      { en: "autonomy", vi: "quyền tự chủ" },
      { en: "collaboration", vi: "hợp tác" },
      { en: "mentorship", vi: "cố vấn" },
      { en: "streamline", vi: "tinh gọn" },
      { en: "procurement", vi: "mua sắm" },
      { en: "restructuring", vi: "tái cấu trúc" },
      { en: "arbitration", vi: "trọng tài" },
      { en: "compliance", vi: "tuân thủ" },
      { en: "governance", vi: "quản trị" },
      { en: "entrepreneurship", vi: "tinh thần khởi nghiệp" },
      { en: "synergy", vi: "hiệp lực" },
      { en: "bureaucracy", vi: "quan liêu" },
      { en: "conglomerate", vi: "tập đoàn" },
      { en: "stakeholder", vi: "bên liên quan" },
      { en: "incentive", vi: "khuyến khích" },
    ],
    C2: [
      { en: "meritocracy", vi: "chế độ tài năng" },
      { en: "oligopoly", vi: "độc quyền nhóm" },
      { en: "monopsony", vi: "độc quyền mua" },
      { en: "leverage", vi: "đòn bẩy" },
      { en: "due diligence", vi: "thẩm định" },
      { en: "fiduciary", vi: "ủy thác" },
      { en: "indemnity", vi: "bồi thường" },
      { en: "liability", vi: "trách nhiệm pháp lý" },
      { en: "remuneration", vi: "thù lao" },
      { en: "outsourcing", vi: "thuê ngoài" },
      { en: "conglomerate", vi: "tập đoàn" },
      { en: "bureaucracy", vi: "quan liêu" },
      { en: "synergy", vi: "hiệp lực" },
      { en: "procurement", vi: "mua sắm" },
      { en: "restructuring", vi: "tái cấu trúc" },
      { en: "arbitration", vi: "trọng tài" },
      { en: "compliance", vi: "tuân thủ" },
      { en: "governance", vi: "quản trị" },
      { en: "entrepreneurship", vi: "khởi nghiệp" },
      { en: "due diligence", vi: "thẩm định" },
    ],
  },

  // ==========================================
  // TRAVEL - Du lịch
  // ==========================================
  TRAVEL: {
    A1: [
      { en: "hotel", vi: "khách sạn" },
      { en: "plane", vi: "máy bay" },
      { en: "ticket", vi: "vé" },
      { en: "bag", vi: "túi" },
      { en: "map", vi: "bản đồ" },
      { en: "beach", vi: "bãi biển" },
      { en: "trip", vi: "chuyến đi" },
      { en: "go", vi: "đi" },
      { en: "see", vi: "xem" },
      { en: "eat", vi: "ăn" },
      { en: "car", vi: "xe hơi" },
      { en: "bus", vi: "xe buýt" },
      { en: "train", vi: "tàu hỏa" },
      { en: "road", vi: "con đường" },
      { en: "city", vi: "thành phố" },
      { en: "sun", vi: "mặt trời" },
      { en: "sea", vi: "biển" },
      { en: "photo", vi: "ảnh" },
      { en: "fun", vi: "vui" },
      { en: "happy", vi: "hạnh phúc" },
    ],
    A2: [
      { en: "airport", vi: "sân bay" },
      { en: "passport", vi: "hộ chiếu" },
      { en: "luggage", vi: "hành lý" },
      { en: "booking", vi: "đặt chỗ" },
      { en: "tourist", vi: "du khách" },
      { en: "guide", vi: "hướng dẫn viên" },
      { en: "flight", vi: "chuyến bay" },
      { en: "resort", vi: "khu nghỉ dưỡng" },
      { en: "souvenir", vi: "quà lưu niệm" },
      { en: "departure", vi: "khởi hành" },
      { en: "arrival", vi: "đến" },
      { en: "visa", vi: "thị thực" },
      { en: "customs", vi: "hải quan" },
      { en: "delay", vi: "trì hoãn" },
      { en: "seat", vi: "ghế" },
      { en: "gate", vi: "cổng" },
      { en: "room", vi: "phòng" },
      { en: "key", vi: "chìa khóa" },
      { en: "tour", vi: "chuyến tham quan" },
      { en: "hotel", vi: "khách sạn" },
    ],
    B1: [
      { en: "reservation", vi: "đặt chỗ" },
      { en: "itinerary", vi: "lịch trình" },
      { en: "destination", vi: "điểm đến" },
      { en: "accommodation", vi: "chỗ ở" },
      { en: "sightseeing", vi: "ngắm cảnh" },
      { en: "backpack", vi: "ba lô" },
      { en: "excursion", vi: "chuyến dã ngoại" },
      { en: "boarding", vi: "lên máy bay" },
      { en: "transit", vi: "quá cảnh" },
      { en: "layover", vi: "dừng chân" },
      { en: "immigration", vi: "nhập cảnh" },
      { en: "hospitality", vi: "hiếu khách" },
      { en: "cuisine", vi: "ẩm thực" },
      { en: "authentic", vi: "chính gốc" },
      { en: "sustainable", vi: "bền vững" },
      { en: "local", vi: "địa phương" },
      { en: "adventure", vi: "phiêu lưu" },
      { en: "visa", vi: "thị thực" },
      { en: "customs", vi: "hải quan" },
      { en: "delay", vi: "trì hoãn" },
    ],
    B2: [
      { en: "embark", vi: "lên tàu" },
      { en: "expedition", vi: "thám hiểm" },
      { en: "sojourn", vi: "lưu trú tạm" },
      { en: "pilgrimage", vi: "hành hương" },
      { en: "vagabond", vi: "người lang thang" },
      { en: "cosmopolitan", vi: "quốc tế" },
      { en: "itinerant", vi: "lưu động" },
      { en: "peregrination", vi: "cuộc du hành" },
      { en: "locale", vi: "địa điểm" },
      { en: "ambience", vi: "không khí" },
      { en: "secluded", vi: "hẻo lánh" },
      { en: "transit", vi: "quá cảnh" },
      { en: "hospitality", vi: "hiếu khách" },
      { en: "cuisine", vi: "ẩm thực" },
      { en: "authentic", vi: "chính gốc" },
      { en: "sustainable", vi: "bền vững" },
      { en: "layover", vi: "dừng chân" },
      { en: "visa", vi: "thị thực" },
      { en: "immigration", vi: "nhập cảnh" },
      { en: "excursion", vi: "dã ngoại" },
    ],
    C1: [
      { en: "peripatetic", vi: "lang bạt" },
      { en: "peregrinate", vi: "du hành" },
      { en: "wayfarer", vi: "lữ khách" },
      { en: "globetrotter", vi: "người đi khắp thế giới" },
      { en: "peregrine", vi: "ngoại lai" },
      { en: "wayfaring", vi: "đi đường" },
      { en: "transcontinental", vi: "xuyên lục địa" },
      { en: "sojourn", vi: "lưu trú" },
      { en: "pilgrimage", vi: "hành hương" },
      { en: "vagabond", vi: "lang thang" },
      { en: "cosmopolitan", vi: "quốc tế" },
      { en: "itinerant", vi: "lưu động" },
      { en: "peregrination", vi: "du hành" },
      { en: "locale", vi: "địa điểm" },
      { en: "ambience", vi: "không khí" },
      { en: "secluded", vi: "hẻo lánh" },
      { en: "excursion", vi: "dã ngoại" },
      { en: "itinerary", vi: "lịch trình" },
      { en: "excursion", vi: "dã ngoại" },
      { en: "globetrotter", vi: "người đi khắp thế giới" },
    ],
    C2: [
      { en: "circumnavigate", vi: "đi vòng quanh" },
      { en: "peregrinity", vi: "sự du hành" },
      { en: "nomadic", vi: "du mục" },
      { en: "vagabondage", vi: "cuộc sống lang thang" },
      { en: "peripateticism", vi: "tính lang bạt" },
      { en: "peregrinator", vi: "người du hành" },
      { en: "peregrinism", vi: "sự du hành" },
      { en: "peripatetic", vi: "lang bạt" },
      { en: "peregrinate", vi: "du hành" },
      { en: "wayfarer", vi: "lữ khách" },
      { en: "globetrotter", vi: "người đi khắp thế giới" },
      { en: "peregrine", vi: "ngoại lai" },
      { en: "wayfaring", vi: "đi đường" },
      { en: "peregrination", vi: "cuộc du hành" },
      { en: "itinerant", vi: "lưu động" },
      { en: "nomadic", vi: "du mục" },
      { en: "vagabondage", vi: "lang thang" },
      { en: "peripateticism", vi: "lang bạt" },
      { en: "peregrinator", vi: "du hành" },
      { en: "peregrinism", vi: "du hành" },
    ],
  },

  // ==========================================
  // SHOPPING - Mua sắm
  // ==========================================
  SHOPPING: {
    A1: [
      { en: "shop", vi: "cửa hàng" },
      { en: "buy", vi: "mua" },
      { en: "money", vi: "tiền" },
      { en: "price", vi: "giá" },
      { en: "cheap", vi: "rẻ" },
      { en: "expensive", vi: "đắt" },
      { en: "pay", vi: "trả tiền" },
      { en: "bag", vi: "túi" },
      { en: "market", vi: "chợ" },
      { en: "store", vi: "cửa hàng" },
      { en: "sell", vi: "bán" },
      { en: "cost", vi: "giá" },
      { en: "cash", vi: "tiền mặt" },
      { en: "card", vi: "thẻ" },
      { en: "size", vi: "kích cỡ" },
      { en: "color", vi: "màu" },
      { en: "new", vi: "mới" },
      { en: "old", vi: "cũ" },
      { en: "big", vi: "to" },
      { en: "small", vi: "nhỏ" },
    ],
    A2: [
      { en: "supermarket", vi: "siêu thị" },
      { en: "discount", vi: "giảm giá" },
      { en: "receipt", vi: "hóa đơn" },
      { en: "customer", vi: "khách hàng" },
      { en: "product", vi: "sản phẩm" },
      { en: "sale", vi: "khuyến mãi" },
      { en: "tag", vi: "nhãn" },
      { en: "basket", vi: "giỏ" },
      { en: "cart", vi: "xe đẩy" },
      { en: "queue", vi: "hàng đợi" },
      { en: "change", vi: "tiền thối" },
      { en: "coin", vi: "xu" },
      { en: "note", vi: "tờ tiền" },
      { en: "bill", vi: "hóa đơn" },
      { en: "wallet", vi: "ví" },
      { en: "cash", vi: "tiền mặt" },
      { en: "card", vi: "thẻ" },
      { en: "price", vi: "giá" },
      { en: "size", vi: "kích cỡ" },
      { en: "color", vi: "màu" },
    ],
    B1: [
      { en: "bargain", vi: "mặc cả" },
      { en: "purchase", vi: "mua hàng" },
      { en: "refund", vi: "hoàn tiền" },
      { en: "warranty", vi: "bảo hành" },
      { en: "brand", vi: "thương hiệu" },
      { en: "quality", vi: "chất lượng" },
      { en: "delivery", vi: "giao hàng" },
      { en: "checkout", vi: "thanh toán" },
      { en: "voucher", vi: "phiếu giảm giá" },
      { en: "offer", vi: "ưu đãi" },
      { en: "value", vi: "giá trị" },
      { en: "discount", vi: "giảm giá" },
      { en: "sale", vi: "khuyến mãi" },
      { en: "customer", vi: "khách hàng" },
      { en: "product", vi: "sản phẩm" },
      { en: "price", vi: "giá" },
      { en: "cost", vi: "chi phí" },
      { en: "money", vi: "tiền" },
      { en: "pay", vi: "trả" },
      { en: "cart", vi: "xe đẩy" },
    ],
    B2: [
      { en: "consumer", vi: "người tiêu dùng" },
      { en: "retail", vi: "bán lẻ" },
      { en: "wholesale", vi: "bán buôn" },
      { en: "promotion", vi: "khuyến mãi" },
      { en: "loyalty", vi: "khách hàng thân thiết" },
      { en: "transaction", vi: "giao dịch" },
      { en: "inventory", vi: "hàng tồn kho" },
      { en: "merchandise", vi: "hàng hóa" },
      { en: "outlet", vi: "cửa hàng giảm giá" },
      { en: "haggle", vi: "mặc cả" },
      { en: "boutique", vi: "cửa hàng nhỏ" },
      { en: "exorbitant", vi: "cắt cổ" },
      { en: "extravagant", vi: "xa hoa" },
      { en: "frugal", vi: "tiết kiệm" },
      { en: "indulgence", vi: "nuông chiều" },
      { en: "consignment", vi: "ký gửi" },
      { en: "auction", vi: "đấu giá" },
      { en: "expenditure", vi: "chi tiêu" },
      { en: "procurement", vi: "mua sắm" },
      { en: "acquisition", vi: "mua lại" },
    ],
    C1: [
      { en: "pecuniary", vi: "thuộc tiền bạc" },
      { en: "remuneration", vi: "thù lao" },
      { en: "mercantile", vi: "thương mại" },
      { en: "profligate", vi: "hoang phí" },
      { en: "parsimonious", vi: "keo kiệt" },
      { en: "commodification", vi: "thương mại hóa" },
      { en: "consumerism", vi: "chủ nghĩa tiêu dùng" },
      { en: "provenance", vi: "xuất xứ" },
      { en: "opulence", vi: "sự giàu sang" },
      { en: "fiscal", vi: "tài khóa" },
      { en: "expenditure", vi: "chi tiêu" },
      { en: "procurement", vi: "mua sắm" },
      { en: "acquisition", vi: "mua lại" },
      { en: "boutique", vi: "cửa hàng nhỏ" },
      { en: "exorbitant", vi: "cắt cổ" },
      { en: "extravagant", vi: "xa hoa" },
      { en: "frugal", vi: "tiết kiệm" },
      { en: "indulgence", vi: "nuông chiều" },
      { en: "consignment", vi: "ký gửi" },
      { en: "auction", vi: "đấu giá" },
    ],
    C2: [
      { en: "usury", vi: "cho vay nặng lãi" },
      { en: "peculation", vi: "tham ô" },
      { en: "defalcation", vi: "biển thủ" },
      { en: "emolument", vi: "thù lao" },
      { en: "lucre", vi: "lợi nhuận" },
      { en: "mammon", vi: "tiền tài" },
      { en: "venality", vi: "hối lộ" },
      { en: "cupidity", vi: "tham lam" },
      { en: "avarice", vi: "keo kiệt" },
      { en: "prodigality", vi: "hoang phí" },
      { en: "pecuniary", vi: "tiền bạc" },
      { en: "remuneration", vi: "thù lao" },
      { en: "mercantile", vi: "thương mại" },
      { en: "profligate", vi: "hoang phí" },
      { en: "parsimonious", vi: "keo kiệt" },
      { en: "commodification", vi: "thương mại hóa" },
      { en: "consumerism", vi: "tiêu dùng" },
      { en: "provenance", vi: "xuất xứ" },
      { en: "opulence", vi: "giàu sang" },
      { en: "fiscal", vi: "tài khóa" },
    ],
  },

  // ==========================================
  // FOOD - Đồ ăn
  // ==========================================
  FOOD: {
    A1: [
      { en: "rice", vi: "cơm" },
      { en: "bread", vi: "bánh mì" },
      { en: "water", vi: "nước" },
      { en: "milk", vi: "sữa" },
      { en: "apple", vi: "táo" },
      { en: "egg", vi: "trứng" },
      { en: "meat", vi: "thịt" },
      { en: "fish", vi: "cá" },
      { en: "eat", vi: "ăn" },
      { en: "drink", vi: "uống" },
      { en: "food", vi: "thức ăn" },
      { en: "fruit", vi: "trái cây" },
      { en: "vegetable", vi: "rau" },
      { en: "soup", vi: "súp" },
      { en: "cake", vi: "bánh" },
      { en: "sugar", vi: "đường" },
      { en: "salt", vi: "muối" },
      { en: "tea", vi: "trà" },
      { en: "coffee", vi: "cà phê" },
      { en: "juice", vi: "nước ép" },
    ],
    A2: [
      { en: "restaurant", vi: "nhà hàng" },
      { en: "menu", vi: "thực đơn" },
      { en: "delicious", vi: "ngon" },
      { en: "cook", vi: "nấu" },
      { en: "ingredient", vi: "nguyên liệu" },
      { en: "sweet", vi: "ngọt" },
      { en: "sour", vi: "chua" },
      { en: "spicy", vi: "cay" },
      { en: "breakfast", vi: "bữa sáng" },
      { en: "dinner", vi: "bữa tối" },
      { en: "lunch", vi: "bữa trưa" },
      { en: "snack", vi: "đồ ăn nhẹ" },
      { en: "dessert", vi: "món tráng miệng" },
      { en: "starter", vi: "món khai vị" },
      { en: "main", vi: "món chính" },
      { en: "plate", vi: "đĩa" },
      { en: "bowl", vi: "bát" },
      { en: "knife", vi: "dao" },
      { en: "fork", vi: "dĩa" },
      { en: "spoon", vi: "thìa" },
    ],
    B1: [
      { en: "recipe", vi: "công thức" },
      { en: "flavor", vi: "hương vị" },
      { en: "nutrition", vi: "dinh dưỡng" },
      { en: "vegetarian", vi: "ăn chay" },
      { en: "seafood", vi: "hải sản" },
      { en: "appetizer", vi: "món khai vị" },
      { en: "seasoning", vi: "gia vị" },
      { en: "portion", vi: "khẩu phần" },
      { en: "cuisine", vi: "ẩm thực" },
      { en: "dish", vi: "món ăn" },
      { en: "meal", vi: "bữa ăn" },
      { en: "beverage", vi: "đồ uống" },
      { en: "chef", vi: "đầu bếp" },
      { en: "kitchen", vi: "nhà bếp" },
      { en: "oven", vi: "lò nướng" },
      { en: "fry", vi: "chiên" },
      { en: "boil", vi: "luộc" },
      { en: "ingredient", vi: "nguyên liệu" },
      { en: "snack", vi: "đồ ăn nhẹ" },
      { en: "dessert", vi: "tráng miệng" },
    ],
    B2: [
      { en: "gourmet", vi: "sành ăn" },
      { en: "culinary", vi: "thuộc nấu nướng" },
      { en: "savor", vi: "thưởng thức" },
      { en: "palate", vi: "khẩu vị" },
      { en: "aromatic", vi: "thơm" },
      { en: "succulent", vi: "mọng nước" },
      { en: "garnish", vi: "trang trí món" },
      { en: "simmer", vi: "ninh nhỏ lửa" },
      { en: "marinate", vi: "ướp" },
      { en: "fermentation", vi: "lên men" },
      { en: "gastronomy", vi: "nghệ thuật ẩm thực" },
      { en: "connoisseur", vi: "người sành" },
      { en: "delectable", vi: "ngon tuyệt" },
      { en: "ambrosial", vi: "thơm ngon" },
      { en: "sustenance", vi: "chất dinh dưỡng" },
      { en: "concoction", vi: "món pha chế" },
      { en: "gastronomic", vi: "thuộc ẩm thực" },
      { en: "piquant", vi: "cay nồng" },
      { en: "satiate", vi: "làm no" },
      { en: "epicurean", vi: "sành ăn" },
    ],
    C1: [
      { en: "gastronome", vi: "người sành ăn" },
      { en: "nourishment", vi: "dinh dưỡng" },
      { en: "palatable", vi: "ngon miệng" },
      { en: "gustatory", vi: "thuộc vị giác" },
      { en: "sapid", vi: "có vị" },
      { en: "esculent", vi: "ăn được" },
      { en: "comestible", vi: "thực phẩm" },
      { en: "victuals", vi: "lương thực" },
      { en: "gustation", vi: "sự nếm" },
      { en: "alimentary", vi: "thuộc dinh dưỡng" },
      { en: "epicurean", vi: "sành ăn" },
      { en: "gastronomy", vi: "ẩm thực" },
      { en: "connoisseur", vi: "người sành" },
      { en: "delectable", vi: "ngon tuyệt" },
      { en: "ambrosial", vi: "thơm ngon" },
      { en: "sustenance", vi: "dinh dưỡng" },
      { en: "concoction", vi: "món pha chế" },
      { en: "gastronomic", vi: "ẩm thực" },
      { en: "piquant", vi: "cay nồng" },
      { en: "satiate", vi: "làm no" },
    ],
    C2: [
      { en: "gastronomist", vi: "chuyên gia ẩm thực" },
      { en: "gastrology", vi: "khoa ẩm thực" },
      { en: "gastronomics", vi: "ẩm thực học" },
      { en: "gastronomically", vi: "về ẩm thực" },
      { en: "gastronome", vi: "người sành ăn" },
      { en: "nourishment", vi: "dinh dưỡng" },
      { en: "palatable", vi: "ngon miệng" },
      { en: "gustatory", vi: "vị giác" },
      { en: "sapid", vi: "có vị" },
      { en: "esculent", vi: "ăn được" },
      { en: "comestible", vi: "thực phẩm" },
      { en: "victuals", vi: "lương thực" },
      { en: "gustation", vi: "nếm" },
      { en: "alimentary", vi: "dinh dưỡng" },
      { en: "gastronomist", vi: "chuyên gia ẩm thực" },
      { en: "gastrology", vi: "khoa ẩm thực" },
      { en: "gastronomics", vi: "ẩm thực học" },
      { en: "gastronomically", vi: "về ẩm thực" },
      { en: "gastronome", vi: "người sành ăn" },
      { en: "nourishment", vi: "dinh dưỡng" },
    ],
  },

  // ==========================================
  // HEALTH - Sức khỏe
  // ==========================================
  HEALTH: {
    A1: [
      { en: "doctor", vi: "bác sĩ" },
      { en: "hospital", vi: "bệnh viện" },
      { en: "medicine", vi: "thuốc" },
      { en: "sick", vi: "ốm" },
      { en: "healthy", vi: "khỏe mạnh" },
      { en: "sleep", vi: "ngủ" },
      { en: "tired", vi: "mệt" },
      { en: "pain", vi: "đau" },
      { en: "head", vi: "đầu" },
      { en: "body", vi: "cơ thể" },
      { en: "nurse", vi: "y tá" },
      { en: "pill", vi: "viên thuốc" },
      { en: "cold", vi: "cảm lạnh" },
      { en: "cough", vi: "ho" },
      { en: "fever", vi: "sốt" },
      { en: "rest", vi: "nghỉ ngơi" },
      { en: "water", vi: "nước" },
      { en: "food", vi: "thức ăn" },
      { en: "walk", vi: "đi bộ" },
      { en: "run", vi: "chạy" },
    ],
    A2: [
      { en: "exercise", vi: "tập thể dục" },
      { en: "diet", vi: "chế độ ăn" },
      { en: "checkup", vi: "khám sức khỏe" },
      { en: "symptom", vi: "triệu chứng" },
      { en: "treatment", vi: "điều trị" },
      { en: "recover", vi: "hồi phục" },
      { en: "injury", vi: "chấn thương" },
      { en: "bandage", vi: "băng gạc" },
      { en: "appointment", vi: "cuộc hẹn" },
      { en: "prescription", vi: "đơn thuốc" },
      { en: "pharmacy", vi: "hiệu thuốc" },
      { en: "ambulance", vi: "xe cứu thương" },
      { en: "fever", vi: "sốt" },
      { en: "cold", vi: "cảm" },
      { en: "cough", vi: "ho" },
      { en: "nurse", vi: "y tá" },
      { en: "pain", vi: "đau" },
      { en: "medicine", vi: "thuốc" },
      { en: "doctor", vi: "bác sĩ" },
      { en: "hospital", vi: "bệnh viện" },
    ],
    B1: [
      { en: "nutrition", vi: "dinh dưỡng" },
      { en: "immunity", vi: "miễn dịch" },
      { en: "infection", vi: "nhiễm trùng" },
      { en: "diagnosis", vi: "chẩn đoán" },
      { en: "surgery", vi: "phẫu thuật" },
      { en: "therapy", vi: "trị liệu" },
      { en: "chronic", vi: "mãn tính" },
      { en: "allergy", vi: "dị ứng" },
      { en: "wellness", vi: "khỏe khoắn" },
      { en: "mental", vi: "tinh thần" },
      { en: "stress", vi: "căng thẳng" },
      { en: "habit", vi: "thói quen" },
      { en: "prevention", vi: "phòng ngừa" },
      { en: "recovery", vi: "hồi phục" },
      { en: "healthcare", vi: "chăm sóc sức khỏe" },
      { en: "exercise", vi: "tập thể dục" },
      { en: "diet", vi: "chế độ ăn" },
      { en: "sleep", vi: "ngủ" },
      { en: "treatment", vi: "điều trị" },
      { en: "prescription", vi: "đơn thuốc" },
    ],
    B2: [
      { en: "cardiovascular", vi: "tim mạch" },
      { en: "metabolism", vi: "trao đổi chất" },
      { en: "inflammation", vi: "viêm" },
      { en: "vaccine", vi: "vắc-xin" },
      { en: "epidemic", vi: "dịch bệnh" },
      { en: "hygiene", vi: "vệ sinh" },
      { en: "obesity", vi: "béo phì" },
      { en: "sedentary", vi: "ít vận động" },
      { en: "rehabilitation", vi: "phục hồi chức năng" },
      { en: "prognosis", vi: "tiên lượng" },
      { en: "pathology", vi: "bệnh lý" },
      { en: "degenerative", vi: "thoái hóa" },
      { en: "therapeutic", vi: "trị liệu" },
      { en: "epidemiology", vi: "dịch tễ học" },
      { en: "immunization", vi: "chủng ngừa" },
      { en: "holistic", vi: "toàn diện" },
      { en: "benign", vi: "lành tính" },
      { en: "malignant", vi: "ác tính" },
      { en: "chronic", vi: "mãn tính" },
      { en: "mental", vi: "tinh thần" },
    ],
    C1: [
      { en: "etiology", vi: "nguyên nhân bệnh" },
      { en: "pathogenic", vi: "gây bệnh" },
      { en: "prophylaxis", vi: "dự phòng" },
      { en: "convalescence", vi: "dưỡng bệnh" },
      { en: "palliative", vi: "giảm đau" },
      { en: "iatrogenic", vi: "do điều trị" },
      { en: "nosocomial", vi: "bệnh viện" },
      { en: "comorbidity", vi: "bệnh kèm" },
      { en: "efficacy", vi: "hiệu quả" },
      { en: "pathophysiology", vi: "sinh lý bệnh" },
      { en: "prognosis", vi: "tiên lượng" },
      { en: "pathology", vi: "bệnh lý" },
      { en: "degenerative", vi: "thoái hóa" },
      { en: "therapeutic", vi: "trị liệu" },
      { en: "epidemiology", vi: "dịch tễ" },
      { en: "immunization", vi: "chủng ngừa" },
      { en: "holistic", vi: "toàn diện" },
      { en: "sedentary", vi: "ít vận động" },
      { en: "benign", vi: "lành tính" },
      { en: "malignant", vi: "ác tính" },
    ],
    C2: [
      { en: "idiosyncratic", vi: "đặc ứng" },
      { en: "psychosomatic", vi: "tâm sinh" },
      { en: "immunosuppression", vi: "ức chế miễn dịch" },
      { en: "carcinogenic", vi: "gây ung thư" },
      { en: "neurodegenerative", vi: "thoái hóa thần kinh" },
      { en: "cardiovascular", vi: "tim mạch" },
      { en: "endocrinology", vi: "nội tiết" },
      { en: "gastroenterology", vi: "tiêu hóa" },
      { en: "hematology", vi: "huyết học" },
      { en: "oncology", vi: "ung thư học" },
      { en: "etiology", vi: "nguyên nhân" },
      { en: "pathogenic", vi: "gây bệnh" },
      { en: "prophylaxis", vi: "dự phòng" },
      { en: "convalescence", vi: "dưỡng bệnh" },
      { en: "palliative", vi: "giảm đau" },
      { en: "iatrogenic", vi: "do điều trị" },
      { en: "nosocomial", vi: "bệnh viện" },
      { en: "comorbidity", vi: "bệnh kèm" },
      { en: "efficacy", vi: "hiệu quả" },
      { en: "pathophysiology", vi: "sinh lý bệnh" },
    ],
  },

  // ==========================================
  // EDUCATION - Giáo dục
  // ==========================================
  EDUCATION: {
    A1: [
      { en: "school", vi: "trường học" },
      { en: "teacher", vi: "giáo viên" },
      { en: "student", vi: "học sinh" },
      { en: "book", vi: "sách" },
      { en: "class", vi: "lớp" },
      { en: "learn", vi: "học" },
      { en: "read", vi: "đọc" },
      { en: "write", vi: "viết" },
      { en: "test", vi: "bài kiểm tra" },
      { en: "homework", vi: "bài tập về nhà" },
      { en: "pen", vi: "bút" },
      { en: "pencil", vi: "bút chì" },
      { en: "desk", vi: "bàn học" },
      { en: "chair", vi: "ghế" },
      { en: "board", vi: "bảng" },
      { en: "lesson", vi: "bài học" },
      { en: "study", vi: "học" },
      { en: "play", vi: "chơi" },
      { en: "friend", vi: "bạn" },
      { en: "happy", vi: "vui" },
    ],
    A2: [
      { en: "university", vi: "đại học" },
      { en: "exam", vi: "kỳ thi" },
      { en: "grade", vi: "điểm" },
      { en: "subject", vi: "môn học" },
      { en: "library", vi: "thư viện" },
      { en: "course", vi: "khóa học" },
      { en: "practice", vi: "luyện tập" },
      { en: "knowledge", vi: "kiến thức" },
      { en: "homework", vi: "bài tập" },
      { en: "teacher", vi: "giáo viên" },
      { en: "student", vi: "học sinh" },
      { en: "class", vi: "lớp" },
      { en: "test", vi: "bài kiểm tra" },
      { en: "book", vi: "sách" },
      { en: "read", vi: "đọc" },
      { en: "write", vi: "viết" },
      { en: "learn", vi: "học" },
      { en: "school", vi: "trường" },
      { en: "lesson", vi: "bài học" },
      { en: "study", vi: "học" },
    ],
    B1: [
      { en: "curriculum", vi: "chương trình học" },
      { en: "scholarship", vi: "học bổng" },
      { en: "tuition", vi: "học phí" },
      { en: "lecture", vi: "bài giảng" },
      { en: "assignment", vi: "bài tập" },
      { en: "research", vi: "nghiên cứu" },
      { en: "academic", vi: "học thuật" },
      { en: "graduate", vi: "tốt nghiệp" },
      { en: "major", vi: "chuyên ngành" },
      { en: "semester", vi: "học kỳ" },
      { en: "degree", vi: "bằng cấp" },
      { en: "campus", vi: "khuôn viên" },
      { en: "professor", vi: "giáo sư" },
      { en: "tutor", vi: "gia sư" },
      { en: "exam", vi: "kỳ thi" },
      { en: "grade", vi: "điểm" },
      { en: "subject", vi: "môn học" },
      { en: "course", vi: "khóa học" },
      { en: "study", vi: "học" },
      { en: "library", vi: "thư viện" },
    ],
    B2: [
      { en: "pedagogy", vi: "sư phạm" },
      { en: "assessment", vi: "đánh giá" },
      { en: "cognitive", vi: "nhận thức" },
      { en: "literacy", vi: "biết chữ" },
      { en: "numeracy", vi: "toán học" },
      { en: "thesis", vi: "luận văn" },
      { en: "dissertation", vi: "luận án" },
      { en: "undergraduate", vi: "đại học" },
      { en: "postgraduate", vi: "sau đại học" },
      { en: "faculty", vi: "khoa" },
      { en: "curriculum", vi: "chương trình học" },
      { en: "scholarship", vi: "học bổng" },
      { en: "tuition", vi: "học phí" },
      { en: "lecture", vi: "bài giảng" },
      { en: "assignment", vi: "bài tập" },
      { en: "research", vi: "nghiên cứu" },
      { en: "academic", vi: "học thuật" },
      { en: "graduate", vi: "tốt nghiệp" },
      { en: "major", vi: "chuyên ngành" },
      { en: "semester", vi: "học kỳ" },
    ],
    C1: [
      { en: "epistemology", vi: "nhận thức luận" },
      { en: "pedagogical", vi: "sư phạm" },
      { en: "didactic", vi: "giảng dạy" },
      { en: "empirical", vi: "thực nghiệm" },
      { en: "methodology", vi: "phương pháp luận" },
      { en: "erudite", vi: "uyên bác" },
      { en: "scholarly", vi: "học thuật" },
      { en: "cognition", vi: "nhận thức" },
      { en: "curriculum", vi: "chương trình học" },
      { en: "assessment", vi: "đánh giá" },
      { en: "cognitive", vi: "nhận thức" },
      { en: "literacy", vi: "biết chữ" },
      { en: "numeracy", vi: "toán học" },
      { en: "thesis", vi: "luận văn" },
      { en: "undergraduate", vi: "đại học" },
      { en: "postgraduate", vi: "sau đại học" },
      { en: "faculty", vi: "khoa" },
      { en: "scholarship", vi: "học bổng" },
      { en: "dissertation", vi: "luận án" },
      { en: "pedagogy", vi: "sư phạm" },
    ],
    C2: [
      { en: "epistemological", vi: "nhận thức luận" },
      { en: "paradigm", vi: "mô hình" },
      { en: "heuristic", vi: "khám phá" },
      { en: "andragogy", vi: "sư phạm người lớn" },
      { en: "metacognition", vi: "siêu nhận thức" },
      { en: "scholastic", vi: "kinh viện" },
      { en: "erudition", vi: "uyên bác" },
      { en: "didacticism", vi: "giảng dạy" },
      { en: "pedagogic", vi: "sư phạm" },
      { en: "paradigmatic", vi: "mô hình" },
      { en: "epistemology", vi: "nhận thức luận" },
      { en: "didactic", vi: "giảng dạy" },
      { en: "scholarly", vi: "học thuật" },
      { en: "erudite", vi: "uyên bác" },
      { en: "pedagogical", vi: "sư phạm" },
      { en: "curriculum", vi: "chương trình học" },
      { en: "methodology", vi: "phương pháp luận" },
      { en: "cognition", vi: "nhận thức" },
      { en: "empirical", vi: "thực nghiệm" },
      { en: "paradigm", vi: "mô hình" },
    ],
  },

  // ==========================================
  // TECHNOLOGY - Công nghệ
  // ==========================================
  TECHNOLOGY: {
    A1: [
      { en: "computer", vi: "máy tính" },
      { en: "phone", vi: "điện thoại" },
      { en: "internet", vi: "internet" },
      { en: "email", vi: "thư điện tử" },
      { en: "screen", vi: "màn hình" },
      { en: "click", vi: "nhấp" },
      { en: "type", vi: "gõ" },
      { en: "app", vi: "ứng dụng" },
      { en: "game", vi: "trò chơi" },
      { en: "online", vi: "trực tuyến" },
      { en: "mouse", vi: "chuột" },
      { en: "keyboard", vi: "bàn phím" },
      { en: "tablet", vi: "máy tính bảng" },
      { en: "camera", vi: "máy ảnh" },
      { en: "video", vi: "video" },
      { en: "music", vi: "nhạc" },
      { en: "photo", vi: "ảnh" },
      { en: "chat", vi: "trò chuyện" },
      { en: "phone", vi: "điện thoại" },
      { en: "screen", vi: "màn hình" },
    ],
    A2: [
      { en: "software", vi: "phần mềm" },
      { en: "website", vi: "trang web" },
      { en: "password", vi: "mật khẩu" },
      { en: "download", vi: "tải xuống" },
      { en: "upload", vi: "tải lên" },
      { en: "device", vi: "thiết bị" },
      { en: "battery", vi: "pin" },
      { en: "wireless", vi: "không dây" },
      { en: "digital", vi: "kỹ thuật số" },
      { en: "keyboard", vi: "bàn phím" },
      { en: "computer", vi: "máy tính" },
      { en: "phone", vi: "điện thoại" },
      { en: "internet", vi: "internet" },
      { en: "email", vi: "email" },
      { en: "screen", vi: "màn hình" },
      { en: "click", vi: "nhấp" },
      { en: "type", vi: "gõ" },
      { en: "app", vi: "ứng dụng" },
      { en: "game", vi: "trò chơi" },
      { en: "online", vi: "trực tuyến" },
    ],
    B1: [
      { en: "algorithm", vi: "thuật toán" },
      { en: "database", vi: "cơ sở dữ liệu" },
      { en: "network", vi: "mạng" },
      { en: "programming", vi: "lập trình" },
      { en: "cybersecurity", vi: "an ninh mạng" },
      { en: "cloud", vi: "đám mây" },
      { en: "server", vi: "máy chủ" },
      { en: "interface", vi: "giao diện" },
      { en: "update", vi: "cập nhật" },
      { en: "backup", vi: "sao lưu" },
      { en: "software", vi: "phần mềm" },
      { en: "website", vi: "trang web" },
      { en: "password", vi: "mật khẩu" },
      { en: "download", vi: "tải xuống" },
      { en: "upload", vi: "tải lên" },
      { en: "device", vi: "thiết bị" },
      { en: "battery", vi: "pin" },
      { en: "wireless", vi: "không dây" },
      { en: "digital", vi: "kỹ thuật số" },
      { en: "keyboard", vi: "bàn phím" },
    ],
    B2: [
      { en: "encryption", vi: "mã hóa" },
      { en: "artificial", vi: "nhân tạo" },
      { en: "intelligence", vi: "trí tuệ" },
      { en: "automation", vi: "tự động hóa" },
      { en: "blockchain", vi: "chuỗi khối" },
      { en: "virtual", vi: "ảo" },
      { en: "innovation", vi: "đổi mới" },
      { en: "startup", vi: "khởi nghiệp" },
      { en: "scalability", vi: "khả năng mở rộng" },
      { en: "algorithm", vi: "thuật toán" },
      { en: "database", vi: "cơ sở dữ liệu" },
      { en: "network", vi: "mạng" },
      { en: "programming", vi: "lập trình" },
      { en: "cybersecurity", vi: "an ninh mạng" },
      { en: "cloud", vi: "đám mây" },
      { en: "server", vi: "máy chủ" },
      { en: "interface", vi: "giao diện" },
      { en: "update", vi: "cập nhật" },
      { en: "backup", vi: "sao lưu" },
      { en: "encryption", vi: "mã hóa" },
    ],
    C1: [
      { en: "cryptography", vi: "mật mã học" },
      { en: "interoperability", vi: "khả năng tương tác" },
      { en: "virtualization", vi: "ảo hóa" },
      { en: "compilation", vi: "biên dịch" },
      { en: "abstraction", vi: "trừu tượng" },
      { en: "concurrency", vi: "đồng thời" },
      { en: "latency", vi: "độ trễ" },
      { en: "throughput", vi: "thông lượng" },
      { en: "redundancy", vi: "dự phòng" },
      { en: "protocol", vi: "giao thức" },
      { en: "encryption", vi: "mã hóa" },
      { en: "artificial", vi: "nhân tạo" },
      { en: "intelligence", vi: "trí tuệ" },
      { en: "automation", vi: "tự động hóa" },
      { en: "blockchain", vi: "chuỗi khối" },
      { en: "virtual", vi: "ảo" },
      { en: "innovation", vi: "đổi mới" },
      { en: "startup", vi: "khởi nghiệp" },
      { en: "scalability", vi: "mở rộng" },
      { en: "cryptography", vi: "mật mã" },
    ],
    C2: [
      { en: "heuristic", vi: "khám phá" },
      { en: "asynchronous", vi: "bất đồng bộ" },
      { en: "polymorphism", vi: "đa hình" },
      { en: "encapsulation", vi: "đóng gói" },
      { en: "idempotent", vi: "bất biến" },
      { en: "orthogonal", vi: "trực giao" },
      { en: "ubiquitous", vi: "phổ biến" },
      { en: "paradigm", vi: "mô hình" },
      { en: "deterministic", vi: "xác định" },
      { en: "stochastic", vi: "ngẫu nhiên" },
      { en: "cryptography", vi: "mật mã" },
      { en: "interoperability", vi: "tương tác" },
      { en: "virtualization", vi: "ảo hóa" },
      { en: "compilation", vi: "biên dịch" },
      { en: "abstraction", vi: "trừu tượng" },
      { en: "concurrency", vi: "đồng thời" },
      { en: "latency", vi: "độ trễ" },
      { en: "throughput", vi: "thông lượng" },
      { en: "redundancy", vi: "dự phòng" },
      { en: "protocol", vi: "giao thức" },
    ],
  },

  // ==========================================
  // HOBBIES - Sở thích
  // ==========================================
  HOBBIES: {
    A1: [
      { en: "music", vi: "âm nhạc" },
      { en: "sport", vi: "thể thao" },
      { en: "read", vi: "đọc" },
      { en: "draw", vi: "vẽ" },
      { en: "sing", vi: "hát" },
      { en: "dance", vi: "nhảy" },
      { en: "play", vi: "chơi" },
      { en: "game", vi: "trò chơi" },
      { en: "movie", vi: "phim" },
      { en: "fun", vi: "vui" },
      { en: "run", vi: "chạy" },
      { en: "walk", vi: "đi bộ" },
      { en: "swim", vi: "bơi" },
      { en: "cook", vi: "nấu ăn" },
      { en: "paint", vi: "vẽ" },
      { en: "book", vi: "sách" },
      { en: "song", vi: "bài hát" },
      { en: "ball", vi: "quả bóng" },
      { en: "bike", vi: "xe đạp" },
      { en: "photo", vi: "ảnh" },
    ],
    A2: [
      { en: "painting", vi: "hội họa" },
      { en: "photography", vi: "nhiếp ảnh" },
      { en: "gardening", vi: "làm vườn" },
      { en: "cooking", vi: "nấu ăn" },
      { en: "running", vi: "chạy bộ" },
      { en: "swimming", vi: "bơi lội" },
      { en: "traveling", vi: "du lịch" },
      { en: "collecting", vi: "sưu tầm" },
      { en: "reading", vi: "đọc sách" },
      { en: "cycling", vi: "đạp xe" },
      { en: "music", vi: "âm nhạc" },
      { en: "sport", vi: "thể thao" },
      { en: "read", vi: "đọc" },
      { en: "draw", vi: "vẽ" },
      { en: "sing", vi: "hát" },
      { en: "dance", vi: "nhảy" },
      { en: "play", vi: "chơi" },
      { en: "game", vi: "trò chơi" },
      { en: "movie", vi: "phim" },
      { en: "fun", vi: "vui" },
    ],
    B1: [
      { en: "hobby", vi: "sở thích" },
      { en: "pastime", vi: "trò tiêu khiển" },
      { en: "recreation", vi: "giải trí" },
      { en: "leisure", vi: "thời gian rảnh" },
      { en: "enthusiast", vi: "người đam mê" },
      { en: "amateur", vi: "nghiệp dư" },
      { en: "craft", vi: "thủ công" },
      { en: "workshop", vi: "xưởng" },
      { en: "membership", vi: "thành viên" },
      { en: "volunteer", vi: "tình nguyện" },
      { en: "painting", vi: "hội họa" },
      { en: "photography", vi: "nhiếp ảnh" },
      { en: "gardening", vi: "làm vườn" },
      { en: "cooking", vi: "nấu ăn" },
      { en: "running", vi: "chạy bộ" },
      { en: "swimming", vi: "bơi lội" },
      { en: "traveling", vi: "du lịch" },
      { en: "collecting", vi: "sưu tầm" },
      { en: "reading", vi: "đọc sách" },
      { en: "cycling", vi: "đạp xe" },
    ],
    B2: [
      { en: "calligraphy", vi: "thư pháp" },
      { en: "pottery", vi: "gốm" },
      { en: "instrument", vi: "nhạc cụ" },
      { en: "orchestra", vi: "dàn nhạc" },
      { en: "marathon", vi: "chạy marathon" },
      { en: "journaling", vi: "viết nhật ký" },
      { en: "meditation", vi: "thiền" },
      { en: "yoga", vi: "yoga" },
      { en: "brewery", vi: "nhà máy bia" },
      { en: "hobby", vi: "sở thích" },
      { en: "pastime", vi: "tiêu khiển" },
      { en: "recreation", vi: "giải trí" },
      { en: "leisure", vi: "thời gian rảnh" },
      { en: "enthusiast", vi: "đam mê" },
      { en: "amateur", vi: "nghiệp dư" },
      { en: "craft", vi: "thủ công" },
      { en: "workshop", vi: "xưởng" },
      { en: "membership", vi: "thành viên" },
      { en: "volunteer", vi: "tình nguyện" },
      { en: "photography", vi: "nhiếp ảnh" },
    ],
    C1: [
      { en: "aficionado", vi: "người đam mê" },
      { en: "connoisseur", vi: "người sành" },
      { en: "virtuoso", vi: "bậc thầy" },
      { en: "perspicacious", vi: "sáng suốt" },
      { en: "painstaking", vi: "tỉ mỉ" },
      { en: "meticulous", vi: "tỉ mỉ" },
      { en: "aesthetic", vi: "thẩm mỹ" },
      { en: "improvisation", vi: "ứng tác" },
      { en: "artistry", vi: "nghệ thuật" },
      { en: "avocation", vi: "sở thích" },
      { en: "calligraphy", vi: "thư pháp" },
      { en: "pottery", vi: "gốm" },
      { en: "instrument", vi: "nhạc cụ" },
      { en: "orchestra", vi: "dàn nhạc" },
      { en: "marathon", vi: "marathon" },
      { en: "photography", vi: "nhiếp ảnh" },
      { en: "journaling", vi: "nhật ký" },
      { en: "meditation", vi: "thiền" },
      { en: "yoga", vi: "yoga" },
      { en: "brewery", vi: "nhà máy bia" },
    ],
    C2: [
      { en: "dilettante", vi: "tay ngang" },
      { en: "aesthete", vi: "người thẩm mỹ" },
      { en: "virtuosity", vi: "tài năng" },
      { en: "perspicacity", vi: "sáng suốt" },
      { en: "scrupulous", vi: "tận tâm" },
      { en: "assiduous", vi: "chuyên cần" },
      { en: "eclectic", vi: "đa dạng" },
      { en: "peripatetic", vi: "lang bạt" },
      { en: "catharsis", vi: "thanh lọc" },
      { en: "avocation", vi: "sở thích" },
      { en: "aficionado", vi: "đam mê" },
      { en: "connoisseur", vi: "sành" },
      { en: "virtuoso", vi: "bậc thầy" },
      { en: "perspicacious", vi: "sáng suốt" },
      { en: "painstaking", vi: "tỉ mỉ" },
      { en: "meticulous", vi: "tỉ mỉ" },
      { en: "aesthetic", vi: "thẩm mỹ" },
      { en: "improvisation", vi: "ứng tác" },
      { en: "artistry", vi: "nghệ thuật" },
      { en: "avocation", vi: "sở thích" },
    ],
  },

  // ==========================================
  // DAILY_ROUTINE - Thói quen hàng ngày
  // ==========================================
  DAILY_ROUTINE: {
    A1: [
      { en: "wake", vi: "thức dậy" },
      { en: "sleep", vi: "ngủ" },
      { en: "eat", vi: "ăn" },
      { en: "work", vi: "làm việc" },
      { en: "home", vi: "nhà" },
      { en: "morning", vi: "buổi sáng" },
      { en: "night", vi: "ban đêm" },
      { en: "time", vi: "thời gian" },
      { en: "day", vi: "ngày" },
      { en: "clock", vi: "đồng hồ" },
      { en: "breakfast", vi: "bữa sáng" },
      { en: "lunch", vi: "bữa trưa" },
      { en: "dinner", vi: "bữa tối" },
      { en: "shower", vi: "tắm" },
      { en: "brush", vi: "đánh (răng)" },
      { en: "commute", vi: "đi làm" },
      { en: "schedule", vi: "lịch" },
      { en: "routine", vi: "thói quen" },
      { en: "habit", vi: "thói quen" },
      { en: "weekend", vi: "cuối tuần" },
    ],
    A2: [
      { en: "breakfast", vi: "bữa sáng" },
      { en: "lunch", vi: "bữa trưa" },
      { en: "dinner", vi: "bữa tối" },
      { en: "shower", vi: "tắm" },
      { en: "brush", vi: "đánh răng" },
      { en: "commute", vi: "đi làm" },
      { en: "schedule", vi: "lịch trình" },
      { en: "routine", vi: "thói quen" },
      { en: "habit", vi: "thói quen" },
      { en: "weekend", vi: "cuối tuần" },
      { en: "wake", vi: "thức dậy" },
      { en: "sleep", vi: "ngủ" },
      { en: "eat", vi: "ăn" },
      { en: "work", vi: "làm việc" },
      { en: "home", vi: "nhà" },
      { en: "morning", vi: "buổi sáng" },
      { en: "night", vi: "đêm" },
      { en: "time", vi: "thời gian" },
      { en: "day", vi: "ngày" },
      { en: "clock", vi: "đồng hồ" },
    ],
    B1: [
      { en: "alarm", vi: "báo thức" },
      { en: "chore", vi: "việc nhà" },
      { en: "productivity", vi: "năng suất" },
      { en: "priority", vi: "ưu tiên" },
      { en: "organize", vi: "sắp xếp" },
      { en: "consistent", vi: "kiên định" },
      { en: "discipline", vi: "kỷ luật" },
      { en: "balance", vi: "cân bằng" },
      { en: "leisure", vi: "thư giãn" },
      { en: "breakfast", vi: "bữa sáng" },
      { en: "lunch", vi: "bữa trưa" },
      { en: "dinner", vi: "bữa tối" },
      { en: "shower", vi: "tắm" },
      { en: "brush", vi: "đánh răng" },
      { en: "commute", vi: "đi làm" },
      { en: "schedule", vi: "lịch" },
      { en: "routine", vi: "thói quen" },
      { en: "habit", vi: "thói quen" },
      { en: "weekend", vi: "cuối tuần" },
      { en: "schedule", vi: "lịch trình" },
    ],
    B2: [
      { en: "ritual", vi: "nghi thức" },
      { en: "regimen", vi: "chế độ" },
      { en: "procrastinate", vi: "trì hoãn" },
      { en: "multitask", vi: "đa nhiệm" },
      { en: "delegate", vi: "ủy quyền" },
      { en: "prioritize", vi: "ưu tiên" },
      { en: "efficiency", vi: "hiệu quả" },
      { en: "mindfulness", vi: "chánh niệm" },
      { en: "procrastination", vi: "trì hoãn" },
      { en: "stimulate", vi: "kích thích" },
      { en: "alarm", vi: "báo thức" },
      { en: "chore", vi: "việc nhà" },
      { en: "productivity", vi: "năng suất" },
      { en: "priority", vi: "ưu tiên" },
      { en: "organize", vi: "sắp xếp" },
      { en: "consistent", vi: "kiên định" },
      { en: "discipline", vi: "kỷ luật" },
      { en: "balance", vi: "cân bằng" },
      { en: "leisure", vi: "thư giãn" },
      { en: "ritual", vi: "nghi thức" },
    ],
    C1: [
      { en: "ritualistic", vi: "nghi thức" },
      { en: "methodical", vi: "có phương pháp" },
      { en: "systematic", vi: "hệ thống" },
      { en: "meticulous", vi: "tỉ mỉ" },
      { en: "punctilious", vi: "câu nệ" },
      { en: "conscientious", vi: "tận tâm" },
      { en: "sedentary", vi: "ít vận động" },
      { en: "monotonous", vi: "đơn điệu" },
      { en: "rhythm", vi: "nhịp điệu" },
      { en: "cadence", vi: "nhịp" },
      { en: "ritual", vi: "nghi thức" },
      { en: "regimen", vi: "chế độ" },
      { en: "procrastinate", vi: "trì hoãn" },
      { en: "multitask", vi: "đa nhiệm" },
      { en: "delegate", vi: "ủy quyền" },
      { en: "prioritize", vi: "ưu tiên" },
      { en: "efficiency", vi: "hiệu quả" },
      { en: "mindfulness", vi: "chánh niệm" },
      { en: "procrastination", vi: "trì hoãn" },
      { en: "stimulate", vi: "kích thích" },
    ],
    C2: [
      { en: "quotidian", vi: "hàng ngày" },
      { en: "ritualistic", vi: "nghi thức" },
      { en: "assiduous", vi: "chuyên cần" },
      { en: "inveterate", vi: "lâu năm" },
      { en: "punctilious", vi: "câu nệ" },
      { en: "methodical", vi: "có phương pháp" },
      { en: "regimen", vi: "chế độ" },
      { en: "automatism", vi: "tự động" },
      { en: "habituation", vi: "thói quen" },
      { en: "circadian", vi: "sinh học" },
      { en: "ritualistic", vi: "nghi thức" },
      { en: "methodical", vi: "phương pháp" },
      { en: "systematic", vi: "hệ thống" },
      { en: "meticulous", vi: "tỉ mỉ" },
      { en: "punctilious", vi: "câu nệ" },
      { en: "conscientious", vi: "tận tâm" },
      { en: "sedentary", vi: "ít vận động" },
      { en: "monotonous", vi: "đơn điệu" },
      { en: "rhythm", vi: "nhịp điệu" },
      { en: "cadence", vi: "nhịp" },
    ],
  },

  // ==========================================
  // DAILY_CONVERSATION - Hội thoại hàng ngày
  // ==========================================
  DAILY_CONVERSATION: {
    A1: [
      { en: "hello", vi: "xin chào" },
      { en: "bye", vi: "tạm biệt" },
      { en: "thanks", vi: "cảm ơn" },
      { en: "sorry", vi: "xin lỗi" },
      { en: "please", vi: "làm ơn" },
      { en: "yes", vi: "vâng" },
      { en: "no", vi: "không" },
      { en: "name", vi: "tên" },
      { en: "how", vi: "thế nào" },
      { en: "fine", vi: "khỏe" },
      { en: "good", vi: "tốt" },
      { en: "bad", vi: "tệ" },
      { en: "happy", vi: "vui" },
      { en: "sad", vi: "buồn" },
      { en: "big", vi: "to" },
      { en: "small", vi: "nhỏ" },
      { en: "hot", vi: "nóng" },
      { en: "cold", vi: "lạnh" },
      { en: "new", vi: "mới" },
      { en: "old", vi: "cũ" },
    ],
    A2: [
      { en: "greeting", vi: "lời chào" },
      { en: "introduce", vi: "giới thiệu" },
      { en: "apologize", vi: "xin lỗi" },
      { en: "invite", vi: "mời" },
      { en: "reply", vi: "trả lời" },
      { en: "question", vi: "câu hỏi" },
      { en: "answer", vi: "câu trả lời" },
      { en: "chat", vi: "trò chuyện" },
      { en: "polite", vi: "lịch sự" },
      { en: "welcome", vi: "chào mừng" },
      { en: "hello", vi: "xin chào" },
      { en: "bye", vi: "tạm biệt" },
      { en: "thanks", vi: "cảm ơn" },
      { en: "sorry", vi: "xin lỗi" },
      { en: "please", vi: "làm ơn" },
      { en: "yes", vi: "vâng" },
      { en: "no", vi: "không" },
      { en: "name", vi: "tên" },
      { en: "how", vi: "thế nào" },
      { en: "fine", vi: "khỏe" },
    ],
    B1: [
      { en: "small talk", vi: "chuyện phiếm" },
      { en: "compliment", vi: "khen ngợi" },
      { en: "opinion", vi: "ý kiến" },
      { en: "agree", vi: "đồng ý" },
      { en: "disagree", vi: "không đồng ý" },
      { en: "suggest", vi: "đề xuất" },
      { en: "request", vi: "yêu cầu" },
      { en: "respond", vi: "phản hồi" },
      { en: "topic", vi: "chủ đề" },
      { en: "manners", vi: "cách cư xử" },
      { en: "greeting", vi: "lời chào" },
      { en: "introduce", vi: "giới thiệu" },
      { en: "apologize", vi: "xin lỗi" },
      { en: "invite", vi: "mời" },
      { en: "reply", vi: "trả lời" },
      { en: "question", vi: "câu hỏi" },
      { en: "answer", vi: "câu trả lời" },
      { en: "chat", vi: "trò chuyện" },
      { en: "polite", vi: "lịch sự" },
      { en: "welcome", vi: "chào mừng" },
    ],
    B2: [
      { en: "rapport", vi: "quan hệ tốt" },
      { en: "empathy", vi: "đồng cảm" },
      { en: "acknowledge", vi: "công nhận" },
      { en: "assertive", vi: "quyết đoán" },
      { en: "gesture", vi: "cử chỉ" },
      { en: "intonation", vi: "ngữ điệu" },
      { en: "paraphrase", vi: "diễn giải" },
      { en: "clarify", vi: "làm rõ" },
      { en: "interject", vi: "ngắt lời" },
      { en: "mediator", vi: "trung gian" },
      { en: "small talk", vi: "chuyện phiếm" },
      { en: "compliment", vi: "khen" },
      { en: "opinion", vi: "ý kiến" },
      { en: "agree", vi: "đồng ý" },
      { en: "disagree", vi: "không đồng ý" },
      { en: "suggest", vi: "đề xuất" },
      { en: "request", vi: "yêu cầu" },
      { en: "respond", vi: "phản hồi" },
      { en: "topic", vi: "chủ đề" },
      { en: "manners", vi: "cư xử" },
    ],
    C1: [
      { en: "eloquent", vi: "hùng biện" },
      { en: "articulate", vi: "rõ ràng" },
      { en: "discourse", vi: "diễn ngôn" },
      { en: "nuance", vi: "sắc thái" },
      { en: "diplomatic", vi: "ngoại giao" },
      { en: "facetious", vi: "đùa cợt" },
      { en: "repartee", vi: "đối đáp" },
      { en: "colloquial", vi: "thông tục" },
      { en: "innuendo", vi: "ám chỉ" },
      { en: "rhetoric", vi: "tu từ" },
      { en: "rapport", vi: "quan hệ" },
      { en: "empathy", vi: "đồng cảm" },
      { en: "acknowledge", vi: "công nhận" },
      { en: "assertive", vi: "quyết đoán" },
      { en: "gesture", vi: "cử chỉ" },
      { en: "intonation", vi: "ngữ điệu" },
      { en: "paraphrase", vi: "diễn giải" },
      { en: "clarify", vi: "làm rõ" },
      { en: "interject", vi: "ngắt lời" },
      { en: "mediator", vi: "trung gian" },
    ],
    C2: [
      { en: "perspicacious", vi: "sáng suốt" },
      { en: "loquacious", vi: "nói nhiều" },
      { en: "garrulous", vi: "ba hoa" },
      { en: "taciturn", vi: "ít nói" },
      { en: "philippic", vi: "diễn văn" },
      { en: "circumlocution", vi: "nói vòng" },
      { en: "verbiage", vi: "dài dòng" },
      { en: "laconic", vi: "ngắn gọn" },
      { en: "soliloquy", vi: "độc thoại" },
      { en: "solipsistic", vi: "duy ngã" },
      { en: "eloquent", vi: "hùng biện" },
      { en: "articulate", vi: "rõ ràng" },
      { en: "discourse", vi: "diễn ngôn" },
      { en: "nuance", vi: "sắc thái" },
      { en: "diplomatic", vi: "ngoại giao" },
      { en: "facetious", vi: "đùa" },
      { en: "repartee", vi: "đối đáp" },
      { en: "colloquial", vi: "thông tục" },
      { en: "innuendo", vi: "ám chỉ" },
      { en: "rhetoric", vi: "tu từ" },
    ],
  },

  // ==========================================
  // RESTAURANT - Nhà hàng
  // ==========================================
  RESTAURANT: {
    A1: [
      { en: "menu", vi: "thực đơn" },
      { en: "food", vi: "đồ ăn" },
      { en: "drink", vi: "đồ uống" },
      { en: "eat", vi: "ăn" },
      { en: "water", vi: "nước" },
      { en: "table", vi: "bàn" },
      { en: "chair", vi: "ghế" },
      { en: "pay", vi: "trả tiền" },
      { en: "order", vi: "gọi món" },
      { en: "happy", vi: "vui" },
      { en: "waiter", vi: "bồi bàn" },
      { en: "bill", vi: "hóa đơn" },
      { en: "tip", vi: "tiền tip" },
      { en: "plate", vi: "đĩa" },
      { en: "fork", vi: "dĩa" },
      { en: "knife", vi: "dao" },
      { en: "spoon", vi: "thìa" },
      { en: "glass", vi: "ly" },
      { en: "cup", vi: "tách" },
      { en: "napkin", vi: "khăn ăn" },
    ],
    A2: [
      { en: "waiter", vi: "bồi bàn" },
      { en: "order", vi: "gọi món" },
      { en: "bill", vi: "hóa đơn" },
      { en: "reservation", vi: "đặt bàn" },
      { en: "dish", vi: "món ăn" },
      { en: "dessert", vi: "tráng miệng" },
      { en: "starter", vi: "khai vị" },
      { en: "main", vi: "món chính" },
      { en: "tip", vi: "tiền tip" },
      { en: "service", vi: "dịch vụ" },
      { en: "menu", vi: "thực đơn" },
      { en: "food", vi: "đồ ăn" },
      { en: "drink", vi: "đồ uống" },
      { en: "eat", vi: "ăn" },
      { en: "water", vi: "nước" },
      { en: "table", vi: "bàn" },
      { en: "chair", vi: "ghế" },
      { en: "pay", vi: "trả" },
      { en: "order", vi: "gọi" },
      { en: "happy", vi: "vui" },
    ],
    B1: [
      { en: "appetizer", vi: "khai vị" },
      { en: "beverage", vi: "đồ uống" },
      { en: "cuisine", vi: "ẩm thực" },
      { en: "chef", vi: "đầu bếp" },
      { en: "specialty", vi: "đặc sản" },
      { en: "recommendation", vi: "gợi ý" },
      { en: "portion", vi: "khẩu phần" },
      { en: "seasoning", vi: "gia vị" },
      { en: "cutlery", vi: "dao nĩa" },
      { en: "atmosphere", vi: "không khí" },
      { en: "waiter", vi: "bồi bàn" },
      { en: "order", vi: "gọi món" },
      { en: "bill", vi: "hóa đơn" },
      { en: "reservation", vi: "đặt bàn" },
      { en: "dish", vi: "món ăn" },
      { en: "dessert", vi: "tráng miệng" },
      { en: "starter", vi: "khai vị" },
      { en: "main", vi: "món chính" },
      { en: "tip", vi: "tiền tip" },
      { en: "service", vi: "dịch vụ" },
    ],
    B2: [
      { en: "gourmet", vi: "sành ăn" },
      { en: "sommelier", vi: "chuyên gia rượu" },
      { en: "ambience", vi: "không khí" },
      { en: "gastronomy", vi: "ẩm thực" },
      { en: "delectable", vi: "ngon" },
      { en: "palatable", vi: "ngon miệng" },
      { en: "garnish", vi: "trang trí" },
      { en: "aroma", vi: "hương" },
      { en: "connoisseur", vi: "người sành" },
      { en: "patron", vi: "khách quen" },
      { en: "appetizer", vi: "khai vị" },
      { en: "beverage", vi: "đồ uống" },
      { en: "cuisine", vi: "ẩm thực" },
      { en: "chef", vi: "đầu bếp" },
      { en: "specialty", vi: "đặc sản" },
      { en: "recommendation", vi: "gợi ý" },
      { en: "portion", vi: "khẩu phần" },
      { en: "seasoning", vi: "gia vị" },
      { en: "cutlery", vi: "dao nĩa" },
      { en: "atmosphere", vi: "không khí" },
    ],
    C1: [
      { en: "epicurean", vi: "sành ăn" },
      { en: "haute cuisine", vi: "ẩm thực cao cấp" },
      { en: "savory", vi: "mặn mà" },
      { en: "ambrosial", vi: "thơm ngon" },
      { en: "gastronomic", vi: "ẩm thực" },
      { en: "piquant", vi: "cay nồng" },
      { en: "satiate", vi: "làm no" },
      { en: "gustatory", vi: "vị giác" },
      { en: "gourmet", vi: "sành ăn" },
      { en: "sommelier", vi: "chuyên rượu" },
      { en: "ambience", vi: "không khí" },
      { en: "gastronomy", vi: "ẩm thực" },
      { en: "delectable", vi: "ngon" },
      { en: "palatable", vi: "ngon" },
      { en: "garnish", vi: "trang trí" },
      { en: "aroma", vi: "hương" },
      { en: "connoisseur", vi: "sành" },
      { en: "patron", vi: "khách quen" },
      { en: "epicurean", vi: "sành ăn" },
      { en: "haute cuisine", vi: "ẩm thực cao cấp" },
    ],
    C2: [
      { en: "gastronome", vi: "người sành ăn" },
      { en: "esculent", vi: "ăn được" },
      { en: "victuals", vi: "lương thực" },
      { en: "comestible", vi: "thực phẩm" },
      { en: "alimentary", vi: "dinh dưỡng" },
      { en: "gustation", vi: "nếm" },
      { en: "sapid", vi: "có vị" },
      { en: "palatable", vi: "ngon" },
      { en: "nourishment", vi: "dinh dưỡng" },
      { en: "gastronomy", vi: "ẩm thực" },
      { en: "epicurean", vi: "sành ăn" },
      { en: "haute cuisine", vi: "ẩm thực cao cấp" },
      { en: "connoisseur", vi: "sành" },
      { en: "delectable", vi: "ngon" },
      { en: "savory", vi: "mặn mà" },
      { en: "ambrosial", vi: "thơm ngon" },
      { en: "gastronomic", vi: "ẩm thực" },
      { en: "piquant", vi: "cay nồng" },
      { en: "satiate", vi: "làm no" },
      { en: "gustatory", vi: "vị giác" },
    ],
  },

  // ==========================================
  // SCHOOL - Trường học
  // ==========================================
  SCHOOL: {
    A1: [
      { en: "class", vi: "lớp" },
      { en: "teacher", vi: "giáo viên" },
      { en: "student", vi: "học sinh" },
      { en: "book", vi: "sách" },
      { en: "pen", vi: "bút" },
      { en: "desk", vi: "bàn" },
      { en: "chair", vi: "ghế" },
      { en: "test", vi: "bài kiểm tra" },
      { en: "read", vi: "đọc" },
      { en: "write", vi: "viết" },
      { en: "school", vi: "trường" },
      { en: "learn", vi: "học" },
      { en: "lesson", vi: "bài học" },
      { en: "board", vi: "bảng" },
      { en: "pencil", vi: "bút chì" },
      { en: "ruler", vi: "thước" },
      { en: "bag", vi: "cặp" },
      { en: "friend", vi: "bạn" },
      { en: "play", vi: "chơi" },
      { en: "happy", vi: "vui" },
    ],
    A2: [
      { en: "subject", vi: "môn học" },
      { en: "homework", vi: "bài tập" },
      { en: "library", vi: "thư viện" },
      { en: "uniform", vi: "đồng phục" },
      { en: "bell", vi: "chuông" },
      { en: "playground", vi: "sân chơi" },
      { en: "classmate", vi: "bạn cùng lớp" },
      { en: "grade", vi: "điểm" },
      { en: "notebook", vi: "vở" },
      { en: "class", vi: "lớp" },
      { en: "teacher", vi: "giáo viên" },
      { en: "student", vi: "học sinh" },
      { en: "book", vi: "sách" },
      { en: "pen", vi: "bút" },
      { en: "desk", vi: "bàn" },
      { en: "chair", vi: "ghế" },
      { en: "test", vi: "bài kiểm tra" },
      { en: "read", vi: "đọc" },
      { en: "write", vi: "viết" },
      { en: "lesson", vi: "bài học" },
    ],
    B1: [
      { en: "curriculum", vi: "chương trình học" },
      { en: "semester", vi: "học kỳ" },
      { en: "schedule", vi: "thời khóa biểu" },
      { en: "assignment", vi: "bài tập" },
      { en: "extracurricular", vi: "ngoại khóa" },
      { en: "principal", vi: "hiệu trưởng" },
      { en: "attendance", vi: "điểm danh" },
      { en: "discipline", vi: "kỷ luật" },
      { en: "tutor", vi: "gia sư" },
      { en: "counselor", vi: "cố vấn" },
      { en: "subject", vi: "môn học" },
      { en: "homework", vi: "bài tập" },
      { en: "lesson", vi: "bài học" },
      { en: "library", vi: "thư viện" },
      { en: "uniform", vi: "đồng phục" },
      { en: "bell", vi: "chuông" },
      { en: "playground", vi: "sân chơi" },
      { en: "classmate", vi: "bạn cùng lớp" },
      { en: "grade", vi: "điểm" },
      { en: "notebook", vi: "vở" },
    ],
    B2: [
      { en: "assessment", vi: "đánh giá" },
      { en: "academic", vi: "học thuật" },
      { en: "scholarship", vi: "học bổng" },
      { en: "thesis", vi: "luận văn" },
      { en: "research", vi: "nghiên cứu" },
      { en: "pedagogy", vi: "sư phạm" },
      { en: "literacy", vi: "biết chữ" },
      { en: "numeracy", vi: "toán học" },
      { en: "faculty", vi: "khoa" },
      { en: "undergraduate", vi: "đại học" },
      { en: "curriculum", vi: "chương trình học" },
      { en: "semester", vi: "học kỳ" },
      { en: "schedule", vi: "thời khóa biểu" },
      { en: "assignment", vi: "bài tập" },
      { en: "extracurricular", vi: "ngoại khóa" },
      { en: "principal", vi: "hiệu trưởng" },
      { en: "attendance", vi: "điểm danh" },
      { en: "discipline", vi: "kỷ luật" },
      { en: "tutor", vi: "gia sư" },
      { en: "counselor", vi: "cố vấn" },
    ],
    C1: [
      { en: "epistemology", vi: "nhận thức luận" },
      { en: "didactic", vi: "giảng dạy" },
      { en: "scholarly", vi: "học thuật" },
      { en: "erudite", vi: "uyên bác" },
      { en: "pedagogical", vi: "sư phạm" },
      { en: "methodology", vi: "phương pháp luận" },
      { en: "cognition", vi: "nhận thức" },
      { en: "empirical", vi: "thực nghiệm" },
      { en: "paradigm", vi: "mô hình" },
      { en: "assessment", vi: "đánh giá" },
      { en: "academic", vi: "học thuật" },
      { en: "scholarship", vi: "học bổng" },
      { en: "thesis", vi: "luận văn" },
      { en: "research", vi: "nghiên cứu" },
      { en: "pedagogy", vi: "sư phạm" },
      { en: "literacy", vi: "biết chữ" },
      { en: "numeracy", vi: "toán học" },
      { en: "faculty", vi: "khoa" },
      { en: "undergraduate", vi: "đại học" },
      { en: "curriculum", vi: "chương trình học" },
    ],
    C2: [
      { en: "scholastic", vi: "kinh viện" },
      { en: "erudition", vi: "uyên bác" },
      { en: "heuristic", vi: "khám phá" },
      { en: "metacognition", vi: "siêu nhận thức" },
      { en: "andragogy", vi: "sư phạm người lớn" },
      { en: "epistemological", vi: "nhận thức luận" },
      { en: "didacticism", vi: "giảng dạy" },
      { en: "pedagogic", vi: "sư phạm" },
      { en: "paradigmatic", vi: "mô hình" },
      { en: "epistemology", vi: "nhận thức luận" },
      { en: "didactic", vi: "giảng dạy" },
      { en: "scholarly", vi: "học thuật" },
      { en: "erudite", vi: "uyên bác" },
      { en: "pedagogical", vi: "sư phạm" },
      { en: "curriculum", vi: "chương trình học" },
      { en: "methodology", vi: "phương pháp luận" },
      { en: "cognition", vi: "nhận thức" },
      { en: "empirical", vi: "thực nghiệm" },
      { en: "paradigm", vi: "mô hình" },
      { en: "scholastic", vi: "kinh viện" },
    ],
  },

  // ==========================================
  // FRIENDS - Bạn bè
  // ==========================================
  FRIENDS: {
    A1: [
      { en: "friend", vi: "bạn" },
      { en: "play", vi: "chơi" },
      { en: "talk", vi: "nói chuyện" },
      { en: "happy", vi: "vui" },
      { en: "fun", vi: "vui vẻ" },
      { en: "like", vi: "thích" },
      { en: "love", vi: "yêu" },
      { en: "share", vi: "chia sẻ" },
      { en: "help", vi: "giúp" },
      { en: "smile", vi: "cười" },
      { en: "kind", vi: "tốt bụng" },
      { en: "nice", vi: "tốt" },
      { en: "good", vi: "tốt" },
      { en: "best", vi: "nhất" },
      { en: "together", vi: "cùng nhau" },
      { en: "chat", vi: "trò chuyện" },
      { en: "laugh", vi: "cười" },
      { en: "meet", vi: "gặp" },
      { en: "visit", vi: "thăm" },
      { en: "gift", vi: "quà" },
    ],
    A2: [
      { en: "friendship", vi: "tình bạn" },
      { en: "chat", vi: "trò chuyện" },
      { en: "hang out", vi: "đi chơi" },
      { en: "together", vi: "cùng nhau" },
      { en: "trust", vi: "tin tưởng" },
      { en: "support", vi: "hỗ trợ" },
      { en: "laugh", vi: "cười" },
      { en: "invite", vi: "mời" },
      { en: "visit", vi: "thăm" },
      { en: "gift", vi: "quà" },
      { en: "friend", vi: "bạn" },
      { en: "play", vi: "chơi" },
      { en: "talk", vi: "nói" },
      { en: "happy", vi: "vui" },
      { en: "fun", vi: "vui" },
      { en: "like", vi: "thích" },
      { en: "love", vi: "yêu" },
      { en: "share", vi: "chia sẻ" },
      { en: "help", vi: "giúp" },
      { en: "smile", vi: "cười" },
    ],
    B1: [
      { en: "companion", vi: "bạn đồng hành" },
      { en: "loyalty", vi: "trung thành" },
      { en: "confide", vi: "tâm sự" },
      { en: "understanding", vi: "thấu hiểu" },
      { en: "empathy", vi: "đồng cảm" },
      { en: "bond", vi: "gắn kết" },
      { en: "memories", vi: "kỷ niệm" },
      { en: "reunion", vi: "đoàn tụ" },
      { en: "acquaintance", vi: "người quen" },
      { en: "companionship", vi: "tình bạn" },
      { en: "friendship", vi: "tình bạn" },
      { en: "chat", vi: "trò chuyện" },
      { en: "hang out", vi: "đi chơi" },
      { en: "together", vi: "cùng nhau" },
      { en: "trust", vi: "tin" },
      { en: "support", vi: "hỗ trợ" },
      { en: "laugh", vi: "cười" },
      { en: "invite", vi: "mời" },
      { en: "visit", vi: "thăm" },
      { en: "gift", vi: "quà" },
    ],
    B2: [
      { en: "camaraderie", vi: "tình bạn thân" },
      { en: "solidarity", vi: "đoàn kết" },
      { en: "confidant", vi: "bạn tâm giao" },
      { en: "reciprocity", vi: "có qua có lại" },
      { en: "genuine", vi: "chân thành" },
      { en: "mutual", vi: "tương hỗ" },
      { en: "bonding", vi: "gắn kết" },
      { en: "clique", vi: "nhóm nhỏ" },
      { en: "soulmate", vi: "tri kỷ" },
      { en: "companionable", vi: "hòa đồng" },
      { en: "companion", vi: "bạn đồng hành" },
      { en: "loyalty", vi: "trung thành" },
      { en: "confide", vi: "tâm sự" },
      { en: "understanding", vi: "thấu hiểu" },
      { en: "empathy", vi: "đồng cảm" },
      { en: "bond", vi: "gắn kết" },
      { en: "memories", vi: "kỷ niệm" },
      { en: "reunion", vi: "đoàn tụ" },
      { en: "acquaintance", vi: "người quen" },
      { en: "companionship", vi: "tình bạn" },
    ],
    C1: [
      { en: "confidante", vi: "bạn tâm giao (nữ)" },
      { en: "platonic", vi: "thuần khiết" },
      { en: "amity", vi: "tình hữu nghị" },
      { en: "convivial", vi: "vui vẻ" },
      { en: "affinity", vi: "sự đồng điệu" },
      { en: "congenial", vi: "hợp nhau" },
      { en: "gregarious", vi: "thích giao du" },
      { en: "solitude", vi: "cô đơn" },
      { en: "kinship", vi: "họ hàng" },
      { en: "fraternity", vi: "tình anh em" },
      { en: "camaraderie", vi: "tình bạn" },
      { en: "solidarity", vi: "đoàn kết" },
      { en: "confidant", vi: "bạn tâm giao" },
      { en: "reciprocity", vi: "có qua có lại" },
      { en: "genuine", vi: "chân thành" },
      { en: "mutual", vi: "tương hỗ" },
      { en: "bonding", vi: "gắn kết" },
      { en: "clique", vi: "nhóm nhỏ" },
      { en: "soulmate", vi: "tri kỷ" },
      { en: "companionable", vi: "hòa đồng" },
    ],
    C2: [
      { en: "conviviality", vi: "vui vẻ" },
      { en: "gregariousness", vi: "thích giao du" },
      { en: "congeniality", vi: "hợp nhau" },
      { en: "affinity", vi: "đồng điệu" },
      { en: "solipsistic", vi: "duy ngã" },
      { en: "amiable", vi: "thân thiện" },
      { en: "amicable", vi: "hòa nhã" },
      { en: "sociable", vi: "hòa đồng" },
      { en: "fraternize", vi: "kết thân" },
      { en: "camaraderie", vi: "tình bạn" },
      { en: "conviviality", vi: "vui vẻ" },
      { en: "gregariousness", vi: "giao du" },
      { en: "congeniality", vi: "hợp" },
      { en: "affinity", vi: "đồng điệu" },
      { en: "solipsistic", vi: "duy ngã" },
      { en: "amiable", vi: "thân thiện" },
      { en: "amicable", vi: "hòa nhã" },
      { en: "sociable", vi: "hòa đồng" },
      { en: "fraternize", vi: "kết thân" },
      { en: "camaraderie", vi: "tình bạn" },
    ],
  },
};

// ==========================================
// HELPER FUNCTIONS
// ==========================================

/**
 * Lấy gợi ý từ vựng theo topic + level.
 * Trả về mảng object { en, vi }
 */
export function getVocabSuggestions(topic, level) {
  if (!topic || !level) return [];
  const topicData = VOCAB_SUGGESTIONS[topic.toUpperCase()];
  if (!topicData) return [];
  return topicData[level] || topicData.A2 || [];
}

/**
 * Shuffle mảng (Fisher-Yates)
 */
export function shuffleArray(arr) {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

/**
 * Lấy gợi ý + shuffle + giới hạn số lượng (mặc định 20).
 * Trả về mảng object { en, vi }
 */
export function getRandomVocabSuggestions(topic, level, limit = 20) {
  const all = getVocabSuggestions(topic, level);
  const shuffled = shuffleArray(all);
  return shuffled.slice(0, limit);
}

export function getAllTopics() {
  return Object.keys(VOCAB_SUGGESTIONS);
}

export function getLevelsForTopic(topic) {
  if (!topic) return [];
  const topicData = VOCAB_SUGGESTIONS[topic.toUpperCase()];
  if (!topicData) return [];
  return Object.keys(topicData);
}

export default {
  VOCAB_SUGGESTIONS,
  getVocabSuggestions,
  shuffleArray,
  getRandomVocabSuggestions,
  getAllTopics,
  getLevelsForTopic,
};
